### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by gsingh93** [sikher/sikher#1]
While the stylized font looks nice, I think a more simple font would increase readability.

**Comment by jasdeepkhalsa** [comment]
We agree that readability is somewhat affected by the use of the Prabhki font but beauty is also important to us in this app, so perhaps we can:
* Leave Prabhki as the default font
* Give an option to change the default font to something else more readable in Settings?

What are your thoughts?

**Comment by gsingh93** [comment]
I'd be fine with that, although my preference would be to have the readable font as the default (on the premise that most people who regularly use the app would prefer the readable version).

I'd be happy either way.

**Comment by irvanjit** [comment]
I agree that the font should be readable by default. I would think that for something like the presentation mode, Prabhki would be more suitable

**Comment by jasdeepkhalsa** [comment]
Readability depends upon the device. For mobiles, a plainer font is more readable, for Desktops, Tablets and the Web - it can afford to be more stylish i.e. Prabhki. So you guys are right, a plainer font should be the default (since it's a mobile-first approach) and we can add an option in Settings to change it to Prabhki
