### ISSUE TITLE
Search is very slow on iOS

### ISSUE THREAD

**Issue by sukhpalsingh** [sikher/sikher#14]
For searching by first letters is taking a long time to return the results.

Need to speed up the search as it takes sometime more than minute.

**Comment by jasdeepkhalsa** [comment]
On which platform? I'm guessing you mean web?

**Comment by sukhpalsingh** [comment]
i am trying in iPhone as i am trying to release to App Strore soon i get the certificates sorted out.

**Comment by jasdeepkhalsa** [comment]
That's good news! Is the app working without any further changes on iOS? I would have thought it would at least require several changes before it would work on iOS properly. It's possibly slow as it may be falling back to use sql.js to process results instead of the native SQLite access functionality which would be really slow.

To make it work on iOS properly you would need to:

* Try to get the file paths on iOS to resolve correctly, currently they only resolve for Android. Inside `services.js` (https://github.com/sikher/sikher/blob/master/www/js/services.js), try to get the `URLResolver` factory to resolve the correct path to the database file https://github.com/sikher/sikher/blob/master/www/sikher.db in iOS. You can use the function `isMobile.iOS()` to detect all iOS devices
* Access the SQLite database on iOS using the $window.sqlitePlugin plugin which should already be installed. Inside `services.js`, in the factory Scripture, it is currently detecting only `isMobile.Android()` to use the sqlitePlugin, you should change this to `if(isMobile.Android() || isMobile.iOS()) { ... }`. Further documentation is available here: https://github.com/litehelpers/Cordova-sqlite-storage in case some specific options need to be added for iOS.

**Comment by jasdeepkhalsa** [comment]
Also if submitting to iOS, do submit it under an organisation named `Sikher` so people know its the official app. You can copy any specific details from the Google Play listing here: https://play.google.com/store/apps/details?id=com.sikher.sikher

**Comment by sukhpalsingh** [comment]
It is working fine otherwise. On minor issue came on build but i commented the line which was creating and issue and worked all good.

I will use Sikher name as organisation then for the release.

I will try to look at the hints you given me to make it fast.

**Comment by sukhpalsingh** [comment]
using isMobile.iOS() improved the speed a lot. thanks for the suggestion.

But still i think it takes atleast one second and some times 2-3 seconds to search by first gurmukhi letters. I tried android app for sikher too and it is giving me same speed now as i am getting in iphone after the above fix.

**Comment by jasdeepkhalsa** [comment]
I think this is perfect for now if it's at parity with the speed of the Android release.

In the future we can try further optimisations on the database side (using procedures) to speed up the results further.

**Comment by sukhpalsingh** [comment]
Agree. I just submitted the app for review now to the app store. Once it is approved we will have it available for users to download for iPhone and IPad through App Store.
