### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by gsingh93** [sikher/sikher#2]
First of all, thanks for doing this. Having an application like this be opensource is something I've wanted for years. I'm really happy someone's finally done this.

From doing mobile development for a while, I've never seen a case where a non-native app has decent performance. Non-native apps are great for cross-platform compatibility, but they sacrifice a lot when it comes to performance. Sometimes that's OK, because the app isn't doing anything intensive that causes a delay of more than a second. I think in this case, where a large database has to be searched, it's significant.

Maybe the reason is because the app is new and there hasn't been any focus on optimizations yet, but the app runs fairly slowly on my Nexus 4. It's performance doesn't compare to other apps like Gurbani Searcher.

My opinion is the Android app should be a native Android app written in Java. Thoughts?

**Comment by jasdeepkhalsa** [comment]
Thanks for raising the issue - yes performance on mobile is a bit of an issue right now and this is down to a number of reasons which mainly revolve around accessing and caching the SQLite database (which is about 50MB):
* We are currently not using a native way of accessing the SQLite database which we could do via a plugin like the [Cordova/PhoneGap SQLitePlugin](http://plugins.cordova.io/#/package/com.triarc.sqliteplugin) this would speed up searching marginally but create messiness in the codebase so we are not keen on this route
* We do not have a good caching mechanism in place - currently we are exploring the use of [Application Cache](http://www.html5rocks.com/en/tutorials/appcache/beginner/) and/or [Service Workers](http://www.html5rocks.com/en/tutorials/service-worker/introduction/) and/or via the [File API](https://github.com/apache/cordova-plugin-file/blob/master/doc/index.md). This by itself will have the biggest performance impact in the app bringing it to near-native performance

The fact also is that Web technology is improving rapidly (e.g. Web Workers, Service Workers etc.) and more powerful smartphones are coming out - so we're building for the future instead of just the now. My prediction is that non-native will reach native performance within the next 5-10 years and then everyone will revert to the approach I've taken with this app - a monolithic Cordova-like codebase which supports every platform out of the box!

So, there's definitely no plans for going down the native route - we think it's quite an old school way to think about development actually - though we also have limited resources and want to have maximum impact for our work.

I'm using the app on a Nexus 5 and most searches happen within 7-8 seconds. I think that's a reasonable tradeoff to have for now until we have a specific performance sprint where we look at a better caching and accessing mechanism for the SQLite database that will mostly solve this issue.

**Comment by gsingh93** [comment]
I think 5-10 years is a long time to wait for the performance gap to be filled. But if you think that caching will fix the performance issues, then I'll believe you.

**Comment by jasdeepkhalsa** [comment]
Yes, if you try the web version in Firefox for example, it's lightening fast. Firefox I believe has some built-in way of caching the SQLite database. Unfortunately though, the UI isn't very well cross-browser tested so parts of it don't work properly in FF.
