### ISSUE TITLE
Add Punjabi Keyboard

### ISSUE THREAD

**Issue by gsingh93** [sikher/sikher#3]
This is probably already on your roadmap, but I'll add an issue for it anyway. There needs to be a punjabi keyboard to search for shabads.

**Comment by jasdeepkhalsa** [comment]
Right now it's not required as it's only first letter search by transliteration

If we decide to add first letter search by gurmukhi we may add this - but for the additional bloat on the UI it's really not worth it (unless someone can come up with a really compelling reason to add first letter search by gurmukhi?)

**Comment by gsingh93** [comment]
Transliteration search is hard to use if you don't know what english letters correspond to which Punjabi letters. For example, I had to search for the shabad [Uthat Baithat Sovat Jagat](http://igurbani.com/?shabadid=293&id=4046). With a punjabi keyboard I would have found it quickly. With the english keyboard, I first tried "obsj", then "ubsj", and then I remembered that "a" usually corresponds to an "oora" on english keyboards (which isn't consistent with all fonts by the way). I finally found the shabad with "absj".

**Comment by irvanjit** [comment]
I think that to be able to search by first Gurmukhi character probably qualifies as a must-have for any Gurbani search app. It's not just a matter of inconsistency with English to Gurmukhi keyboard mappings, but there is no one correct transliteration because we are attempting to write a language in a completely different script and phonetics will always vary person to person. Even if a consensus is made with regards to keyboard mappings and phonetics, there would still be no standardized transliteration or translation that can be held as supreme because we have derived it ourselves from our own knowledge of the modern English alphabet and language but the Gurmukhi script comes straight from the guru, thus it holds supreme.

As for a dedicated keyboard, I don't think any application should have to depend on a third-party in order to be fully functional (if Gurmukhi-first letter search is added), so while one would still be able to use the feature on both major mobile platforms via third-party keyboards, there should still be an out-of-the-box solution (again another minimum I think for any Gurbani search app).

**Comment by jasdeepkhalsa** [comment]
Some good points here! I agree that having the Gurmukhi letters show up will reduce confusion as to which shabad you're searching for. However, one way or another ultimately you'll still have to map Gurmukhi to English characters because the physical keyboard you type with has English characters.

What we can do though is switch to using Gurmukhi first letter search but there will be no on-screen keyboard - once you type with your keyboard the Gurmukhi characters will show up - if you need to see which keys relate to which letter you can refer to a keyboard map image which shows you how the qwerty maps to the Gurmukhi letters. Hopefully, though it should be so intuitive that you should never need to look at it.

Again, I don't wish to reinvent an entirely new keyboard, I want people to use their default keyboard for their device and yet still be able to type Gurmukhi characters for doing the search.
